<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <!-- <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> -->
        <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json;
            https://nuget.samboy.dev/v3/index.json;
            https://polymod.dev/nuget/v3/index.json;
        </RestoreAdditionalProjectSources>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Archipelago.MultiClient.Net" Version="6.7.1" />
        <PackageReference Include="PolyMod" Version="*" />
    </ItemGroup>
</Project>
